import Head from "next/head";
import Image from "next/image";
import { useMoralis } from "react-moralis";
function Login() {
  const { authenticate, isAuthenticating } = useMoralis();
  return (
    <div className="bg-black">
      <Head>
        <title>Giga Blog | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/2.png" />
      </Head>
      <main className="">
        <div className="bg-[url(/assets/bg2.png)] bg-cover w-full h-screen">
          <div className="flex justify-between">
            <div className="relative h-36 w-36 ml-6 ">
              <Image alt="logo" src="/assets/3.png" layout="fill" />
            </div>
            <div className="m-10">
              <button
                onClick={authenticate}
                className="px-20 py-3 rounded-xl text-xl text-white font-semibold bg-gigablue hover:brightness-95 animate-bounce"
              >
                {isAuthenticating ? "loading..." : "Login"}
              </button>
            </div>
          </div>
          <div>
            <p className="text-gigaskin contrast-125 ml-5 mt-32 text-justify leading-tight font-semibold text-4xl max-w-xl">
              Giga Blog is a Bloging Platform for Everyone to Share their
              Thoughts and Ideas. It is World&apos;s First Web 3.0 Based Bloging
              Platform.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}

export default Login;
