import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useMoralis, useMoralisQuery } from "react-moralis";
import Header from "../components/Header";
import Login from "../components/Login";
import MainScreen from "../components/MainScreen";
import Sidebar from "../components/Sidebar";

function Blog() {
  const { data, loading, error } = useMoralisQuery(
    "Posts",
    (query) => query.descending("createdAt"),
    [],
    {
      live: true,
    }
  );

  const router = useRouter();

  const { id } = router.query;

  const { isAuthenticated, logout } = useMoralis();

  if (!isAuthenticated) return <Login />;
  return (
    <div className="bg-white dark:bg-gigadark">
      <Head>
        <title>Giga Blog | </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/2.png" />
      </Head>
      <main className="flex flex-grow">
        <Sidebar />
        <div className="flex-1">
          <Header />
          {data.map((post) => {
            const WhichPost = post.id === id;
            if (WhichPost) {
              return (
                <div
                  key={post.id}
                  className="bg-gray-100 dark:bg-gigalightpurple p-5 m-5 rounded-xl"
                >
                  <h1 className="text-gigadark dark:text-white text-center text-4xl font-mono font-semibold">
                    {post.get("title")}
                  </h1>
                  <p className="text-gigadark dark:text-gray-100 text-left m-5 text-lg font-mono font-semibold">
                    {post.get("content")}
                  </p>
                  <div className="text-center">
                    <Image
                      src={post.get("image")}
                      width={600}
                      height={400}
                      objectFit="cover"
                      className="rounded-xl"
                    />
                  </div>
                  <div className="flex space-x-4 m-5 mt-10 bg-gray-200 dark:bg-gigadark p-3 w-72 rounded-full">
                    <Image
                      src={post.get("profilePic")}
                      height={70}
                      width={70}
                      objectFit="cover"
                    />
                    <h1 className="text-gigadark dark:text-white text-lg font-mono font-semibold my-auto">
                      {post.get("username")}
                    </h1>
                  </div>
                </div>
              );
            }
          })}
        </div>
      </main>
    </div>
  );
}

export default Blog;
